### PR TITLE
fix: 🐛 correct useAutoHeight logic and return type

### LINKED ISSUE #37: useAutoHeight returns autoHeight as undefined
We're consuming this hook in SQFormScrollableCard, and when that component's prop `isSelfBounding` has the value `true`, we use the return value `autoHeight` from `useAutoHeight` and apply it to the container <div>'s height style. When we log the value of `autoHeight` when we consume it `SQFormScrollableCard`, however, it shows that it's `undefined`, which appears to be a bug. 

[loom video](https://www.loom.com/share/71ba9e4e0d6e4ce1afec2f47eac3051c)

### PR DESCRIPTION
**Pull request by jamesgriffith9519**
add a return type for the useAutoheight hook as well as adjust a small
logic change that corrects an issue where we are returning a broken
height amount.

✅ Closes: #37

## Checklist

- [x] Tests for the changes have been added (for bug fixes / features) and all tests are passing
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

## What is the current behavior?

It seems if the useAutoHeight cannot find a style value for "paddingBottom" on the parent container, it will break the calculation being used to determine the overall calculated Height. 

Issue: #37 

## What is the new behavior?

- This introduces a simple ternary that returns '0px' is there is no value found for the parent's style prop.

### CODE REVIEW

**Comment by jamesgriffith9519** [comment]
@gdoohen1 hey! I think I had seen a slightly older PR where you were working on this, and you had some questions about the types. I too had run into some issues when I was consuming it so I changed the type from HTMLElement to HTMLDivElement  and it seems to have satisfied the TS compiler, though I'm not sure if this is the best way to handle that, anyways tagging you in case you remember that other PR and to see if you had any input!

File: src/hooks/useAutoHeight.ts [hunk 1]
```diff
@@ -17,7 +21,9 @@ export function useAutoHeight() {
     const offsetBasedHeight = `calc(100vh - ${topOffset}px - 24px)`;
 
     const parentHeight = containerRef.parentElement?.clientHeight;
-    const parentPadding = containerRef.parentElement?.style.paddingBottom;
+    const parentPadding = containerRef?.parentElement?.style.paddingBottom
```
Comment (gdoohen1) [inline src/hooks/useAutoHeight.ts]: This doesn't need to be a ternary since the conditional is the exact same as the truthy evaluation - can just do `const parentPadding = containerRef?.parentElement?.style.paddingBottom || '0px';`

**Comment by gdoohen1** [comment]
> @gdoohen1 hey! I think I had seen a slightly older PR where you were working on this, and you had some questions about the types. I too had run into some issues when I was consuming it so I changed the type from HTMLElement to HTMLDivElement and it seems to have satisfied the TS compiler, though I'm not sure if this is the best way to handle that, anyways tagging you in case you remember that other PR and to see if you had any input!

@jamesgriffith9519 That sounds good to me! I didn't have a particular reason for picking one over the other so whatever makes TS happy without causing the consumer to have to do any casting is great!

**Review by gdoohen1 — APPROVED** [review]

**Comment by lucas-homer** [comment]
Does this mean that anywhere we want to use `useAutoHeight` we'd have to feed the `autoHeight` value to a `div`? In your loom it looks like you had an instance of SQFormScrollabeCard, but it's wrapped in a `div`.

**Comment by jamesgriffith9519** [comment]
> Does this mean that anywhere we want to use `useAutoHeight` we'd have to feed the `autoHeight` value to a `div`? In your loom it looks like you had an instance of SQFormScrollabeCard, but it's wrapped in a `div`.

yes that's correct if I understand your question. It's wrapped in a div in the loom because the scrollableCard component is broken, but normally this is already consumed inside of the component itself and you would not need an additional wrapper div.

**Comment by lucas-homer** [comment]
> > Does this mean that anywhere we want to use `useAutoHeight` we'd have to feed the `autoHeight` value to a `div`? In your loom it looks like you had an instance of SQFormScrollabeCard, but it's wrapped in a `div`.
> 
> yes that's correct if I understand your question. It's wrapped in a div in the loom because the scrollableCard component is broken, but normally this is already consumed inside of the component itself and you would not need an additional wrapper div.

ahhhh ok cool. thank you, that alleviates my concern.

**Review by lucas-homer — APPROVED** [review]
